name: 'SMK Build'
description: 'Creates a docker image for an SMK application'
inputs:
  OPENSHIFT_SERVER_URL:
    description: 'The url to the openshift instance, build process caches info in oc configmaps'
    required: true
  OPENSHIFT_TOKEN_DEV:
    description: 'The openshift token for the service account access to the dev namespace'
    required: true
  GHCR_USER:
    description: 'The github user, required to push docker image to repository packages'
    required: true
  GHCR_TOKEN:
    description: 'the github token, for the user above, again used to push images to github packages'
    required: true
  DOCKER_REGISTRY:
    description: 'the docker registry where the image will be pulled from'
    required: true
runs:
  using: "composite"
  steps: 
    - id: calculateImageTag
      name: calculate Image Tag
      shell: bash
      run: |
        echo ----- CALCULATE IMAGE TAG -----
        repoandorg=${{ github.repository }}
        REPO=$(basename "$repoandorg")
        echo REPO $REPO

        DATESTAMP=$(date +%Y%m%d-%H%M)
        #REGISTRY="docker.pkg.github.com"
        REGISTRY=${{ inputs.DOCKER_REGISTRY }}
        repolowercase=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        IMAGE="${REGISTRY}/$repolowercase/$REPO"
        TAGS="${IMAGE}:${DATESTAMP}"
        LATEST="${IMAGE}:latest"
        
        echo ::set-output name=DOCKER_VERSION_TAG::${TAGS}
        echo ::set-output name=DOCKER_LATEST_TAG::${LATEST}
        echo ::set-output name=TIMESTAMPTAG::${DATESTAMP}
        echo ::set-output name=REPO::${REPO}

        echo event name is $GITHUB_EVENT_NAME
        echo  $DEBUG_DEPLOY      shell: bash

    - id: oc-login
      shell: bash
      run: |
        echo ----- OC-LOGIN -----
        # get oc client
        curl https://downloads-openshift-console.apps.silver.devops.gov.bc.ca/amd64/linux/oc.tar -o oc.tar
        tar -xvf oc.tar
        curdir=$(pwd)
        PATH=$curdir:$PATH
        oc login --token=${{ inputs.OPENSHIFT_TOKEN_DEV }} --server=${{ inputs.OPENSHIFT_SERVER_URL }}

    - name: Store Issue URL in configmap
      id: cacheIssueUrl
      shell: bash
      run: |
        echo github event name ${{ github.event_name }}
        echo CONFMAP_NAME $CONFMAP_NAME
        CONFMAP_NAME=${{ steps.calculateImageTag.outputs.REPO }}-gh-issues-cm
        echo CONFMAP_NAME $CONFMAP_NAME
        ISSUE_URL=$(jq --raw-output .pull_request.issue_url "$GITHUB_EVENT_PATH")
        echo issue url is $ISSUE_URL

        CONF_EXISTS=$(oc get configmaps -o json |  jq '[.items[] | select(.metadata.name == "'$CONFMAP_NAME'")] | length')
        echo CONF_EXISTS $CONF_EXISTS
        if [ $CONF_EXISTS -eq 0 ] 
          then
            methodType="create"
        else
            methodType="replace"
            oc delete configmap $CONFMAP_NAME
        fi
        
        oc create configmap $CONFMAP_NAME \
          --from-literal=issueURL=$ISSUE_URL \
          --from-literal=github_event_path=$GITHUB_EVENT_PATH \
          --from-file=github_event_json=$GITHUB_EVENT_PATH

    - name: Build Docker Image
      shell: bash
      id: buildPushDockerImage
      run: |
        ls -la
        pwd
        # parameterize the docker registry
        GITHUBOWNERREPO=${{ github.repository }}
        GITHHUBREPO=${{ steps.calculateImageTag.outputs.REPO }}
        DOCKER_REPO=${{ steps.calculateImageTag.outputs.DOCKER_VERSION_TAG }}

        echo GITHUBOWNERREPO $GITHUBOWNERREPO
        echo GITHHUBREPO $GITHHUBREPO
        echo DOCKER_REPO $DOCKER_REPO

        #DOCKER_IMAGE_PATH=docker.pkg.github.com/$GITHUBOWNER-REPO/$GITHHUBREPO:

        echo ${{ inputs.GHCR_TOKEN }} | docker login https://${{ inputs.DOCKER_REGISTRY }} -u ${{ inputs.GHCR_USER }} --password-stdin
        docker build -t $DOCKER_REPO .
        docker push $DOCKER_REPO
      
    - name: Cache Image Tag
      shell: bash
      id: cacheImageTag
      run: |
        IMAGETAG=${{ steps.calculateImageTag.outputs.TIMESTAMPTAG }}
        # needs to be made unique to app being deployed
        # CONFMAP_NAME=imagetag2deploy
        CONFMAP_NAME=${{ steps.calculateImageTag.outputs.REPO }}-imagetag-cm
        CONF_EXISTS=$(oc get configmaps -o json |  jq '[.items[] | select(.metadata.name == "'$CONFMAP_NAME'")] | length')
        echo conf exists is $CONF_EXISTS
        echo imagetag is $IMAGETAG
        
        if [ $CONF_EXISTS -eq 0 ] 
          then
            methodType="create"
        else
            methodType="replace"
        fi
        echo methodType is $methodType
        oc create configmap $CONFMAP_NAME --from-literal=current_image_tag=$IMAGETAG --dry-run -o yaml > template.yaml
        oc $methodType -f template.yaml

    - name: Tag the pull request with build tag
      id: tagpullrequest
      shell: bash
      run: |
        DOCKER_VERSION_TAG=${{ steps.calculateImageTag.outputs.TIMESTAMPTAG }}

        echo tag version is $DOCKER_VERSION_TAG
        #pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo github event path: $GITHUB_EVENT_PATH
        echo $GITHUB_WORKSPACE

        # use this for pulls
        issue_url=$(jq --raw-output .pull_request.issue_url "$GITHUB_EVENT_PATH")
        echo issue url is $issue_url

        # for debugging using existing pull_request
        if [ -z "$issue_url" ] || [ "$issue_url" = "null" ]
          then
            issue_url="https://api.github.com/repos/bcgov/smk-fap-fcb/issues/4"
        fi

        # ---- adding the tag that was assigned to the image to the issue ----
        # --header "authorization: Bearer ${{ inputs.GHCR_TOKEN }}" \
        jsonwithlabels=$(curl --header "Content-Type: application/json" \
        -u "$GHCR_USER:$GHCR_TOKEN" \
        --request GET \
        $issue_url | jq '.labels |= . + ["'$DOCKER_VERSION_TAG'"] | {("labels"): .["labels"]?}')
        
        # now send modified json back to the api with the new label
        # looks like gh api doesn't use bearer anymore 
        #         --header "authorization: Bearer ${{ inputs.GITHUB_TOKEN }}" \
        curl \
        --location --request POST $issue_url \
        --header "Content-Type: application/json" \
        -u "$GHCR_USER:$GHCR_TOKEN" \
        --data "$jsonwithlabels"
