# not used by the action, just an example of what the file should look like
services:
- name: smk-fap-fcb-svc
  host: smk-fap-fcb-svc.b16795-dev.svc
  port: 8888
  tags:
  - ns.smk-apps.smk-fap-fcb
  - smk-fap-fcb
  - dev
  routes:
  - name: smk-fap-fcb-route
    hosts: 
    - smk-fap-fcb.api.gov.bc.ca
    methods:
    - GET
    paths:
    - /
    strip_path: false
    tags:
    - OAS3_import
    - ns.smk-apps.smk-fap-fcb

  